In [1]:
import pandas as pd
import warnings as w
import numpy as np

In [2]:
w.filterwarnings('ignore')

We try first load dataset and view the topmost entries

In [3]:
data=pd.read_csv("loan_prediction_dataset.csv")
data.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [4]:
data['Loan_Amount_Term'].max()

480.0

Let's Find shaape of our dataset

In [5]:
data.shape

(614, 13)

data is 367 x 12 ,that means 367 rows and 12 columns
Now, we will fetch whole information about our dataset

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


we can see that some less rows for different columns,now we have to check whether which data-item is null now

In [7]:
data.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

Here,we can see that gender contains 11 null values,dependents contains 10 null values ,self_employed contains 23,LoanAmount contains 5,Loan_Amount_term contains 6 and Credit_history contains 29.
Now we have to fix all these kind of annomalies.

In [8]:
data.isnull().sum()/len(data)

Loan_ID              0.000000
Gender               0.021173
Married              0.004886
Dependents           0.024430
Education            0.000000
Self_Employed        0.052117
ApplicantIncome      0.000000
CoapplicantIncome    0.000000
LoanAmount           0.035831
Loan_Amount_Term     0.022801
Credit_History       0.081433
Property_Area        0.000000
Loan_Status          0.000000
dtype: float64

Lets's go for handle the missing values.

We will drop column Loan_ID ,because there is no need such column here.

In [9]:
data=data.drop('Loan_ID',axis=1)

In [10]:
data.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

Loan_ID column removed , so now we wil handle the missing values by mode,that means most frequent data occured will be inserted in place of missing values.

In [11]:
data['Gender'].unique()

array(['Male', 'Female', nan], dtype=object)

In [12]:
data['Gender'].mode()[0]

'Male'

Most Frequent Value = Male

In [13]:
data['Gender'] = data['Gender'].fillna(data['Gender'].mode()[0])

In [14]:
data.isnull().sum()/len(data)

Gender               0.000000
Married              0.004886
Dependents           0.024430
Education            0.000000
Self_Employed        0.052117
ApplicantIncome      0.000000
CoapplicantIncome    0.000000
LoanAmount           0.035831
Loan_Amount_Term     0.022801
Credit_History       0.081433
Property_Area        0.000000
Loan_Status          0.000000
dtype: float64

In [15]:
data['Education'].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

Gender has been handled ,now we will try for rest.

In [16]:
data['Dependents'].unique()

array(['0', '1', '2', '3+', nan], dtype=object)

In [17]:
data['Dependents'].mode()[0]

'0'

In [18]:
data['Dependents'] = data['Dependents'].fillna(data['Dependents'].mode()[0])

In [19]:
data['Dependents'].unique()

array(['0', '1', '2', '3+'], dtype=object)

In [20]:
data['Self_Employed'].unique()

array(['No', 'Yes', nan], dtype=object)

In [21]:
data['Self_Employed'].mode()

0    No
Name: Self_Employed, dtype: object

In [22]:
data['Self_Employed'] = data['Self_Employed'].fillna(data['Self_Employed'].mode()[0])

In [23]:
data['Self_Employed'].unique()

array(['No', 'Yes'], dtype=object)

In [24]:
data['LoanAmount'].unique()

array([ nan, 128.,  66., 120., 141., 267.,  95., 158., 168., 349.,  70.,
       109., 200., 114.,  17., 125., 100.,  76., 133., 115., 104., 315.,
       116., 112., 151., 191., 122., 110.,  35., 201.,  74., 106., 320.,
       144., 184.,  80.,  47.,  75., 134.,  96.,  88.,  44., 286.,  97.,
       135., 180.,  99., 165., 258., 126., 312., 136., 172.,  81., 187.,
       113., 176., 130., 111., 167., 265.,  50., 210., 175., 131., 188.,
        25., 137., 160., 225., 216.,  94., 139., 152., 118., 185., 154.,
        85., 259., 194.,  93., 370., 182., 650., 102., 290.,  84., 242.,
       129.,  30., 244., 600., 255.,  98., 275., 121.,  63., 700.,  87.,
       101., 495.,  67.,  73., 260., 108.,  58.,  48., 164., 170.,  83.,
        90., 166., 124.,  55.,  59., 127., 214., 240.,  72.,  60., 138.,
        42., 280., 140., 155., 123., 279., 192., 304., 330., 150., 207.,
       436.,  78.,  54.,  89., 143., 105., 132., 480.,  56., 159., 300.,
       376., 117.,  71., 490., 173.,  46., 228., 30

In [25]:
data['LoanAmount'].mode()

0    120.0
Name: LoanAmount, dtype: float64

In [26]:
data['LoanAmount'] = data['LoanAmount'].fillna(data['LoanAmount'].mode()[0]).astype('int')

In [27]:
data['Loan_Amount_Term'].unique()

array([360., 120., 240.,  nan, 180.,  60., 300., 480.,  36.,  84.,  12.])

In [28]:
data['Loan_Amount_Term'].mode()

0    360.0
Name: Loan_Amount_Term, dtype: float64

In [29]:
data['Loan_Amount_Term'] = data['Loan_Amount_Term'].fillna(data['Loan_Amount_Term'].mode()[0]).astype('int')

In [30]:
data['Loan_Amount_Term'].unique()

array([360, 120, 240, 180,  60, 300, 480,  36,  84,  12])

In [31]:
data['Credit_History'].unique()

array([ 1.,  0., nan])

In [32]:
data['Credit_History'].mode()

0    1.0
Name: Credit_History, dtype: float64

In [33]:
data['Credit_History'] = data['Credit_History'].fillna(data['Credit_History'].mode()[0]).astype('int')

In [34]:
data['Married'].unique()

array(['No', 'Yes', nan], dtype=object)

In [35]:
data['Married'].mode()

0    Yes
Name: Married, dtype: object

In [36]:
data['Married'] = data['Married'].fillna(data['Married'].mode()[0])

In [37]:
data['Married'].unique()

array(['No', 'Yes'], dtype=object)

In [38]:
data.isnull().sum()/len(data)

Gender               0.0
Married              0.0
Dependents           0.0
Education            0.0
Self_Employed        0.0
ApplicantIncome      0.0
CoapplicantIncome    0.0
LoanAmount           0.0
Loan_Amount_Term     0.0
Credit_History       0.0
Property_Area        0.0
Loan_Status          0.0
dtype: float64

Now,all missing values are handled successfully

Now,we will handle categorical data cause,Machine learning can only define numerical values.

In [39]:
data['Dependents'].unique()

array(['0', '1', '2', '3+'], dtype=object)

In [40]:
data['Dependents']=data['Dependents'].replace(to_replace="3+",value=4)

we have to convert gender,Married,Education,applicantIncome,Propert_Area and Loan-Status into numerical values

In [41]:
data['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [42]:
data['Gender']=data['Gender'].map({'Male':1,'Female':0})

In [43]:
data['Gender'].unique()

array([1, 0], dtype=int64)

In [44]:
data['Married'].unique()

array(['No', 'Yes'], dtype=object)

In [45]:
data['Married']=data['Married'].map({'Yes':1,'No':0}).astype('int')

In [46]:
data['Married'].unique()

array([0, 1])

In [47]:
data['Education'].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [48]:
data['Education']=data['Education'].map({'Graduate':1,'Not Graduate':0}).astype('int')

In [49]:
data['Education'].unique()

array([1, 0])

In [50]:
data['Self_Employed'].unique()

array(['No', 'Yes'], dtype=object)

In [51]:
data['Self_Employed']=data['Self_Employed'].map({'No':0,'Yes':1}).astype('int')

In [52]:
data['Self_Employed'].unique()


array([0, 1])

In [53]:
data['Property_Area'].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [54]:
data['Property_Area']=data['Property_Area'].map({'Urban':0,'Semiurban':1,'Rural':2})

In [55]:
data['Property_Area'].unique()

array([0, 2, 1], dtype=int64)

In [56]:
data['Loan_Status'].unique()

array(['Y', 'N'], dtype=object)

In [57]:
data['Loan_Status']=data['Loan_Status'].map({'Y':1,'N':0})

In [58]:
data['Loan_Status'].unique()

array([1, 0], dtype=int64)

In [59]:
data.head()

Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0          0          1              0             5849   
1       1        1          1          1              0             4583   
2       1        1          0          1              1             3000   
3       1        1          0          0              0             2583   
4       1        0          0          1              0             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0         120               360               1   
1             1508.0         128               360               1   
2                0.0          66               360               1   
3             2358.0         120               360               1   
4                0.0         141               360               1   

   Property_Area  Loan_Status  
0              0            1  
1              2            0  
2              0            1  
3              0            1  
4              0            1

Now,categorical data has been handled.
Now we will strore feature matrix in 'X' and target vector in 'y'

In [60]:
X = data.drop('Loan_Status',axis=1)
y=data['Loan_Status']

In [61]:
X.isna().sum()/len(X)


Gender               0.0
Married              0.0
Dependents           0.0
Education            0.0
Self_Employed        0.0
ApplicantIncome      0.0
CoapplicantIncome    0.0
LoanAmount           0.0
Loan_Amount_Term     0.0
Credit_History       0.0
Property_Area        0.0
dtype: float64

In [62]:
y

0      1
1      0
2      1
3      1
4      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 614, dtype: int64

Since,some values of the column are not in the range , so we have to perform feature scaling to implement under range,

Coluns are : ApplicantIncome,CoApplicant_Income, Loan_AMount,'Loan_Amount_Term

In [63]:

columns=['ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term']

In [64]:
from sklearn.preprocessing import StandardScaler
s=StandardScaler()
X[columns]=s.fit_transform(X[columns])

In [65]:
data.head()

Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0          0          1              0             5849   
1       1        1          1          1              0             4583   
2       1        1          0          1              1             3000   
3       1        1          0          0              0             2583   
4       1        0          0          1              0             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0         120               360               1   
1             1508.0         128               360               1   
2                0.0          66               360               1   
3             2358.0         120               360               1   
4                0.0         141               360               1   

   Property_Area  Loan_Status  
0              0            1  
1              2            0  
2              0            1  
3              0            1  
4              0            1

Now we will split the dataset into taining set and testing set and apply k fold cross validation

In [66]:
from  sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

proceeding to spliting of train and test of data

In [67]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=72)

In [68]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

Now we will use different kind algos for of Machine Learning

In [69]:
lr=LogisticRegression()
lr.fit(X,y)
sv=svm.SVC()
sv.fit(X,y)
dc=DecisionTreeClassifier()
dc.fit(X,y)
rf=RandomForestClassifier()
rf.fit(X,y)
gb=GradientBoostingClassifier()
gb.fit(X,y)

GradientBoostingClassifier()

Now,we will store prediction of the test data

In [70]:
y_prediction1=lr.predict(X_test)
y_prediction2=sv.predict(X_test)
y_prediction3=dc.predict(X_test)
y_prediction4=rf.predict(X_test)
y_prediction5=gb.predict(X_test)

In [71]:
from sklearn import metrics

Now we will calculate the score of each prediction

In [72]:
score1=metrics.r2_score(y_test,y_prediction1)
score2=metrics.r2_score(y_test,y_prediction2)
score3=metrics.r2_score(y_test,y_prediction3)
score4=metrics.r2_score(y_test,y_prediction4)
score5=metrics.r2_score(y_test,y_prediction5)

Now,whose score will be highest will be selected for the main model

In [73]:
Data=pd.DataFrame({'Models':['LogisticsRegression','SVC','DecisionTreeClassifier','RandomForestClassifier','GradientBoostingClassifier'],"R2-Score":[score1*100,score2*100,score3*100,score3*100,score5*100]})
Data

Models    R2-Score
0         LogisticsRegression   12.929125
1                         SVC   15.490033
2      DecisionTreeClassifier  100.000000
3      RandomForestClassifier  100.000000
4  GradientBoostingClassifier   46.220930

Hypermeter Tuning

In [74]:
from sklearn.model_selection import RandomizedSearchCV

Logistic Regression

In [75]:
log_reg_grid={"C":np.logspace(-4,4,20),"solver":['liblinear']}

In [76]:
rs_log_reg=RandomizedSearchCV(LogisticRegression(),param_distributions=log_reg_grid,n_iter=20,cv=8,verbose=True)

In [77]:
rs_log_reg.fit(X,y)

Fitting 8 folds for each of 20 candidates, totalling 160 fits


RandomizedSearchCV(cv=8, estimator=LogisticRegression(), n_iter=20,
                   param_distributions={'C': array([1.00000000e-04, 2.63665090e-04, 6.95192796e-04, 1.83298071e-03,
       4.83293024e-03, 1.27427499e-02, 3.35981829e-02, 8.85866790e-02,
       2.33572147e-01, 6.15848211e-01, 1.62377674e+00, 4.28133240e+00,
       1.12883789e+01, 2.97635144e+01, 7.84759970e+01, 2.06913808e+02,
       5.45559478e+02, 1.43844989e+03, 3.79269019e+03, 1.00000000e+04]),
                                        'solver': ['liblinear']},
                   verbose=True)

In [78]:
rs_log_reg.best_score_

0.8095095693779905

SVC

In [79]:
SVC_grid={"C":np.logspace(-1,1,20),"kernel":["linear"]}

In [80]:
rs_sv=RandomizedSearchCV(svm.SVC(),param_distributions=SVC_grid,n_iter=20,cv=8,verbose=True)

In [81]:
rs_sv.fit(X,y)

Fitting 8 folds for each of 20 candidates, totalling 160 fits


RandomizedSearchCV(cv=8, estimator=SVC(), n_iter=20,
                   param_distributions={'C': array([ 0.1       ,  0.1274275 ,  0.16237767,  0.20691381,  0.26366509,
        0.33598183,  0.42813324,  0.54555948,  0.6951928 ,  0.88586679,
        1.12883789,  1.43844989,  1.83298071,  2.33572147,  2.97635144,
        3.79269019,  4.83293024,  6.15848211,  7.8475997 , 10.        ]),
                                        'kernel': ['linear']},
                   verbose=True)

In [82]:
rs_sv.best_score_

0.8095095693779905

Still after running the operation of hypertuning , we can get that DecisionTreeClassifier and RandomForestClassifier will be the best.So we move forward with DecisionTreeClassifier.

Now we will go with model of DecisiontreeClassifier 

In [83]:
final_model=RandomForestClassifier()
final_model.fit(X,y)

RandomForestClassifier()

Now,we will save the model for import purpose using joblib library

In [84]:
import joblib

In [85]:
joblib.dump(final_model,'loan_approval_model')

['loan_approval_model']

In [86]:
model_final=joblib.load('loan_approval_model')

In [87]:
df=pd.DataFrame({
    'Gender':1,
    'Married':1,
    'Dependents':2,
    'Education':0,
    'Self_Employed':0,
    'ApplicantIncome':2889,
    'CoapplicantIncome':0,
    'LoanAmount':45,
    'Loan_Amount_Term':180,
    'Credit_History':0,
    'Property_Area':1
},index=[0])

In [88]:
model_final.predict(df)

array([0], dtype=int64)

In [89]:
ans=model_final.predict(df)

In [90]:
if ans==1:
    print("Approved")
else:
    print("NA")

NA
